export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const SET_CHOOSEN_DATE = 'SET_CHOOSEN_DATE';

export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';